apiVersion: v2
appVersion: "latest"
description: Helm chart for deploying SReview
name: sreview
version: 0.1.0
dependencies:
- name: minio
  version: 4.0.2
  repository: "https://charts.min.io/"
  condition: use_internal_minio
- name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 11.6.15
  condition: use_internal_pg
