---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: sreview-ingress
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: sreview.example.com
    http:
      paths:
      - path: 
        backend:
          serviceName: sreview-web
          servicePort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sreview-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sreview-web
  template:
    metadata:
      labels:
        app: sreview-web
    spec:
      containers:
      - name: web
        image: registry.salsa.debian.org/debconf-video-team/sreview/web:main
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: sreview-config
        env:
        - name: SREVIEW_ADMINPW
          valueFrom:
            secretKeyRef:
              name: sreview-secret
              key: SREVIEW_ADMINPW
        - name: SREVIEW_DBISTRING
          valueFrom:
            secretKeyRef:
              name: sreview-secret
              key: SREVIEW_DBISTRING
        - name: SREVIEW_SECRET
          valueFrom:
            secretKeyRef:
              name: sreview-secret
              key: SREVIEW_SECRET
        - name: SREVIEW_API_KEY
          valueFrom:
            secretKeyRef:
              name: sreview-secret
              key: SREVIEW_API_KEY
        livenessProbe:
          httpGet:
            path: /
            port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sreview-web
spec:
  type: NodePort
  selector:
    app: sreview-web
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sreview-master
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manage-jobs
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["batch", "extensions"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manage-jobs
subjects:
- kind: ServiceAccount
  name: sreview-master
  apiGroup: ""
roleRef:
  kind: Role
  name: manage-jobs
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sreview-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sreview-master
  template:
    metadata:
      labels:
        app: sreview-master
    spec:
      serviceAccountName: sreview-master
      containers:
      - name: master
        image: registry.salsa.debian.org/debconf-video-team/sreview/master-kube:main
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: sreview-config
        env:
        - name: SREVIEW_DBISTRING
          valueFrom:
            secretKeyRef:
              name: sreview-secret
              key: SREVIEW_DBISTRING
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: detect
spec:
  concurrencyPolicy: Forbid
  schedule: 0,30 * * * *
  jobTemplate: 
    metadata:
      labels:
        app: sreview-detect
    spec:
      template:
        metadata:
          labels:
            app: sreview-detect
        spec:
          restartPolicy: OnFailure
          containers:
          - name: detect
            image: registry.salsa.debian.org/debconf-video-team/sreview/detect:main
            imagePullPolicy: Always
            command: ["/usr/bin/sreview-detect"]
            envFrom:
            - configMapRef:
                name: sreview-config
            env:
            - name: SREVIEW_DBISTRING
              valueFrom:
                secretKeyRef:
                  name: sreview-secret
                  key: SREVIEW_DBISTRING
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: import
spec:
  concurrencyPolicy: Forbid
  schedule: 0,30 * * * *
  jobTemplate:
    metadata:
      labels:
        app: sreview-import
    spec:
      template:
        metadata:
          labels:
            app: sreview-import
        spec:
          restartPolicy: OnFailure
          containers:
          - name: import
            image: registry.salsa.debian.org/debconf-video-team/sreview/detect:main
            imagePullPolicy: Always
            command: ["/usr/bin/sreview-import"]
            envFrom:
            - configMapRef:
                name: sreview-config
            env:
            - name: SREVIEW_DBISTRING
              valueFrom:
                secretKeyRef:
                  name: sreview-secret
                  key: SREVIEW_DBISTRING
