---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresdata
  labels:
    type: local
spec:
  storageClassName: postgresdata
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/vda1/postgresdata"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio
  labels:
    type: local
spec:
  storageClassName: minio
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/vda1/minio"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresdata
spec:
  storageClassName: postgresdata
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio
spec:
  storageClassName: minio
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
