---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
spec:
  rules:
  - host: {{ .Values.webHostname | default "sreview.example.com" }}
    http:
      paths:
      - path:
        backend:
          serviceName: {{ .Release.Name }}-web
          servicePort: 8080
