---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-master
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-manage-jobs
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["batch", "extensions"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-manage-jobs
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-master
  apiGroup: ""
roleRef:
  kind: Role
  name: {{ .Release.Name }}-manage-jobs
  apiGroup: rbac.authorization.k8s.io
